name: work
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logging: ^1.2.0
  modal_progress_hud_nsn: ^0.4.0
  path_provider: ^2.1.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  go_router: ^12.1.0
  uuid: ^4.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: MPLUSRounded
      fonts:
        - asset: assets/fonts/MPLUSRounded/static/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/MPLUSRounded/static/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/MPLUSRounded/static/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/MPLUSRounded/static/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/MPLUSRounded/static/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/MPLUSRounded/static/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MPLUSRounded/static/MPLUSRounded1c-Black.ttf
          weight: 900

  uses-material-design: true

  assets:
    - images/
